"""updating QuizAnswersHistory table

Revision ID: 40cbd724a46f
Revises: 9667f964713c
Create Date: 2023-07-03 15:01:05.824529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cbd724a46f'
down_revision = '9667f964713c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_answers_history', schema=None) as batch_op:
        batch_op.drop_column('race_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_answers_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_name', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
