"""adding answer table

Revision ID: ea18a33f2e9a
Revises: 
Create Date: 2023-05-22 13:42:05.594026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea18a33f2e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_answers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('q1', sa.String(length=255), nullable=False),
    sa.Column('q2', sa.String(length=255), nullable=False),
    sa.Column('q3', sa.String(length=255), nullable=False),
    sa.Column('q4', sa.String(length=255), nullable=False),
    sa.Column('q5', sa.String(length=255), nullable=False),
    sa.Column('q6', sa.String(length=255), nullable=False),
    sa.Column('q7', sa.String(length=255), nullable=False),
    sa.Column('q8', sa.String(length=255), nullable=False),
    sa.Column('q9', sa.String(length=255), nullable=False),
    sa.Column('q10', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_answers')
    # ### end Alembic commands ###
